- name: KROK 1 – Utwórz/utrzymaj farmę VM w OpenShift Virtualization
  hosts: localhost
  gather_facts: false

  vars_files:
    - group_vars/vms.yml

  collections:
    - kubevirt.core

  vars:
    vm_names: []    # WAŻNE: zawsze zainicjalizowana, choćby pustą listą

  tasks:
    - name: Zbuduj listę nazw VM (testvm-1, testvm-2, ...)
      set_fact:
        vm_names: "{{ vm_names + [ (vm_base_name ~ '-' ~ item) | lower ] }}"
      with_sequence: "start=1 end={{ vm_count | int }}"

    - name: Oczyść nazwy VM zgodnie z RFC1123 (na wszelki wypadek)
      set_fact:
        vm_names: >-
          {{
            vm_names
            | map('regex_replace', '[^a-z0-9-]', '')
            | list
          }}

    - name: DEBUG – pokaż nazwy VM
      debug:
        var: vm_names

    - name: Utwórz/utrzymaj VM (bez ISO)
      loop: "{{ vm_names }}"
      kubevirt_vm:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: "{{ kubevirt_namespace }}"
        name: "{{ item }}"
        labels:
          app: demo-vm-farm
        data_volume_templates:
          - metadata:
              name: "{{ item }}-rootdisk"
            spec:
              source:
                registry:
                  url: "{{ vm_image_registry_url }}"
              storage:
                resources:
                  requests:
                    storage: "{{ vm_disk_size }}"
                accessModes: [ReadWriteOnce]
        running: true
        spec:                # to jest spec.template.spec
          domain:
            resources:
              requests:
                cpu: "{{ vm_cpu }}"
                memory: "{{ vm_memory }}"
            devices:
              disks:
                - name: rootdisk
                  disk:
                    bus: virtio
                - name: cloudinitdisk
                  disk:
                    bus: virtio
          volumes:
            - name: rootdisk
              dataVolume:
                name: "{{ item }}-rootdisk"
            - name: cloudinitdisk
              cloudInitNoCloud:
                userData: |
                  #cloud-config
                  users:
                    - default
                    - name: clouduser
                      sudo: ALL=(ALL) NOPASSWD:ALL
                      groups: users, admin
                      shell: /bin/bash
                      ssh_authorized_keys:
                        - {{ vm_ssh_key }}
                  ssh_pwauth: false
                  disable_root: true
