- name: KROK 2 – Podpięcie ISO (PVC) do wszystkich VM
  hosts: localhost
  gather_facts: false

  vars_files:
    - group_vars/vms.yml

  collections:
    - kubevirt.core

  vars:
    vm_names: []

  tasks:
    - name: Zbuduj listę numerów VM
      set_fact:
        vm_numbers: "{{ range(1, (vm_count | int) + 1) | list }}"

    - name: Zbuduj listę nazw VM
      set_fact:
        vm_names: "{{ vm_names + [ (vm_base_name ~ '-' ~ item) | lower ] }}"
      with_sequence: "start=1 end={{ vm_count | int }}"

    - name: Oczyść nazwy VM zgodnie z RFC1123
      set_fact:
        vm_names: >-
          {{
            vm_names
            | map('regex_replace', '[^a-z0-9-]', '')
            | list
          }}

    - name: DEBUG – nazwy VM
      debug:
        var: vm_names


    # ─────────────────────────────────────────────────────────────
    # Krok podpięcia ISO do każdej VM
    # ─────────────────────────────────────────────────────────────
    - name: Podepnij ISO do VM
      loop: "{{ vm_names }}"
      kubevirt_vm:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: "{{ kubevirt_namespace }}"
        name: "{{ item }}"
        running: true
        data_volume_templates:
          - metadata:
              name: "{{ item }}-rootdisk"
            spec:
              source:
                registry:
