- name: KROK 2 – Podpięcie ISO (PVC) do wszystkich VM
  hosts: localhost
  gather_facts: false

  vars_files:
    - group_vars/vms.yml

  collections:
    - kubevirt.core

  vars:
    vm_names: []

  tasks:
    - name: Zbuduj listę nazw VM (tak samo jak w kroku 1)
      set_fact:
        vm_names: "{{ vm_names + [ (vm_base_name ~ '-' ~ item) | lower ] }}"
      with_sequence: "start=1 end={{ vm_count | int }}"

    - name: Oczyść nazwy VM zgodnie z RFC1123 (na wszelki wypadek)
      set_fact:
        vm_names: >-
          {{
            vm_names
            | map('regex_replace', '[^a-z0-9-]', '')
            | list
          }}

    - name: DEBUG – pokaż nazwy VM
      debug:
        var: vm_names

    - name: Podłącz ISO PVC jako dysk CDROM do każdej VM
      loop: "{{ vm_names }}"
      kubevirt_vm:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: "{{ kubevirt_namespace }}"
        name: "{{ item }}"
        labels:
          app: demo-vm-farm

        # UWAGA: to jest dokładnie ta sama definicja DV co w kroku 1
        data_volume_templates:
          - metadata:
              name: "{{ item }}-rootdisk"
            spec:
              source:
                registry:
                  url: "{{ vm_image_registry_url }}"
              storage:
                resources:
                  requests:
                    storage: "{{ vm_disk_size }}"
                accessModes: [ReadWriteOnce]

        running: true
        spec:                # spec.template.spec
          domain:
            resources:
              requests:
                cpu: "{{ vm_cpu }}"
                memory: "{{ vm_memory }}"
            devices:
              disks:
                - name: rootdisk
                  disk:
                    bus: virtio
                - name: cloudinitdisk
                  disk:
                    bus: virtio
                - name: iso-disk
                  cdrom:
                    bus: sata
          volumes:
            - name: rootdisk
              dataVolume:
                name: "{{ item }}-rootdisk"
            - name: cloudinitdisk
              cloudInitNoCloud:
                userData: |
                  #cloud-config
                  users:
                    - default
                    - name: clouduser
                      sudo: ALL=(ALL) NOPASSWD:ALL
                      groups: users, admin
                      shell: /bin/bash
                      ssh_authorized_keys:
                        - {{ vm_ssh_key }}
                  ssh_pwauth: false
                  disable_root: true
            - name: iso-disk
              persistentVolumeClaim:
                claimName: "{{ vm_iso_pvc_name }}"
