- name: KROK 2 – Podpięcie ISO (PVC) i boot z ISO dla wszystkich VM
  hosts: localhost
  gather_facts: false

  vars_files:
    - group_vars/vms.yml

  collections:
    - kubevirt.core

  vars:
    vm_names: []

  tasks:
    - name: Zbuduj listę nazw VM (tak samo jak w kroku 1)
      set_fact:
        vm_names: "{{ vm_names + [ (vm_base_name ~ '-' ~ item) | lower ] }}"
      with_sequence: "start=1 end={{ vm_count | int }}"

    - name: Oczyść nazwy VM zgodnie z RFC1123
      set_fact:
        vm_names: >-
          {{
            vm_names
            | map('regex_replace', '[^a-z0-9-]', '')
            | list
          }}

    - name: DEBUG – pokaż nazwy VM
      debug:
        var: vm_names

    - name: Podłącz ISO jako dysk CDROM i ustaw boot z ISO
      loop: "{{ vm_names }}"
      kubevirt_vm:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: "{{ kubevirt_namespace }}"
        name: "{{ item }}"
        labels:
          app: demo-vm-farm

        # 👉 Taka sama definicja DataVolume jak w KROKU 1 (pusty dysk)
        data_volume_templates:
          - metadata:
              name: "{{ item }}-rootdisk"
            spec:
              source:
                blank: {}
              storage:
                resources:
                  requests:
                    storage: "{{ vm_disk_size }}"
                accessModes: [ReadWriteOnce]

        # 👉 Teraz chcemy, żeby VM wystartowała z ISO
        running: true

        spec:
          domain:
            resources:
              requests:
                cpu: "{{ vm_cpu }}"
                memory: "{{ vm_memory }}"
            devices:
              disks:
                # 1) ISO – jako CDROM z najwyższym priorytetem bootowania
                - name: iso-disk
                  cdrom:
                    bus: sata
                  bootOrder: 1
                # 2) rootdisk – pusty dysk, drugi w kolejności
                - name: rootdisk
                  disk:
                    bus: virtio
                  bootOrder: 2
                # 3) cloud-init (opcjonalnie, zostawiamy jak było)
                - name: cloudinitdisk
                  disk:
                    bus: virtio
              interfaces:
                - name: default
                  model: virtio
                  masquerade: {}
                - name: vlan214
                  model: virtio
                  bridge: {}

          networks:
            - name: default
              pod: {}
            - name: vlan214
              multus:
                networkName: "default/vlan214-net"

          volumes:
            - name: rootdisk
              dataVolume:
                name: "{{ item }}-rootdisk"
            - name: cloudinitdisk
              cloudInitNoCloud:
                userData: |
                  #cloud-config
                  users:
                    - name: clouduser
                      sudo: ALL=(ALL) NOPASSWD:ALL
                      groups: users, admin
                      shell: /bin/bash
                      ssh_authorized_keys:
                        - {{ vm_ssh_key }}
                  ssh_pwauth: false
                  disable_root: true
            - name: iso-disk
              persistentVolumeClaim:
                claimName: "{{ vm_iso_pvc_name }}"
