- name: Zbierz informacje o maszynach wirtualnych w OpenShift Virtualization
  hosts: localhost
  gather_facts: false

  collections:
    - kubevirt.core

  vars:
    kubeconfig_path: ~/.kube/config
    kubevirt_namespace: proj-vms   # <- zmień na swój namespace

  tasks:
    - name: Pobierz informacje o wszystkich VM w namespace
      kubevirt_vm_info:
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: "{{ kubevirt_namespace }}"
      register: vm_info

    - name: Wypisz podstawowe parametry każdej VM (CPU, RAM, dyski, sieci)
      debug:
        msg: |
          VM: {{ item.metadata.name }}
            Namespace: {{ item.metadata.namespace }}
            Running: {{ item.spec.running | default('unknown') }}
            CPU: {{ item.spec.template.spec.domain.resources.requests.cpu | default('not set') }}
            Memory: {{ item.spec.template.spec.domain.resources.requests.memory | default('not set') }}
            Disks:
              {% for disk in item.spec.template.spec.domain.devices.disks | default([]) %}
              - name: {{ disk.name }}
                type: {{ (disk.keys() | list | difference(['name']))[0] | default('n/a') }}
              {% endfor %}
            Interfaces (spec):
              {% for iface in item.spec.template.spec.domain.devices.interfaces | default([]) %}
              - logical_name: {{ iface.name | default('n/a') }}
                model: {{ iface.model | default('virtio') }}
              {% endfor %}
      loop: "{{ vm_info.resources | default([]) }}"

    # --- MAC + NAZWY INTERFEJSÓW Z VMI ---

    - name: Pobierz informacje o wszystkich VirtualMachineInstance (VMI)
      kubevirt_vmi_info:
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: "{{ kubevirt_namespace }}"
      register: vmi_info

    - name: Wypisz adresy MAC i nazwy interfejsów każdej działającej VM
      debug:
        msg: |
          VMI: {{ item.metadata.name }}
            Node: {{ item.status.nodeName | default('unknown') }}
            Interfejsy (runtime):
              {% for iface in item.status.interfaces | default([]) %}
              - logical_name: {{ iface.name | default('n/a') }}
                guest_if: {{ iface.interfaceName | default('n/a') }}
                mac: {{ iface.mac | default('unknown') }}
                ip: {{ iface.ipAddress | default('n/a') }}
              {% endfor %}
      loop: "{{ vmi_info.resources | default([]) }}"
