- name: Zbierz informacje o maszynach wirtualnych w OpenShift Virtualization
  hosts: localhost
  gather_facts: false

  collections:
    - kubevirt.core

  vars:
    kubeconfig_path: ~/.kube/config
    kubevirt_namespace: testvm   # <- zmień na swój namespace

  tasks:
    - name: Pobierz informacje o wszystkich VM w namespace
      kubevirt_vm_info:
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: "{{ kubevirt_namespace }}"
      register: vm_info

    # --- OGÓLNE INFO O VM (CPU, RAM, dyski itd.) ---

    - name: Wypisz podstawowe parametry każdej VM
      debug:
        msg: |
          VM: {{ item.metadata.name }}
            Namespace: {{ item.metadata.namespace }}
            Running: {{ item.spec.running | default('unknown') }}
            CPU: {{ item.spec.template.spec.domain.resources.requests.cpu | default('not set') }}
            Memory: {{ item.spec.template.spec.domain.resources.requests.memory | default('not set') }}
            Disks:
              {% for disk in item.spec.template.spec.domain.devices.disks | default([]) %}
              - name: {{ disk.name }}
                type: {{ (disk.keys() | list | difference(['name']))[0] | default('n/a') }}
              {% endfor %}
      loop: "{{ vm_info.resources | default([]) }}"

    # --- OSOBNY TASK: INTERFEJSY + MAC Z *SPEC* VM (DZIAŁA TEŻ DLA WYŁĄCZONYCH) ---

    - name: Wypisz interfejsy i adresy MAC z definicji VM (działa też dla wyłączonych)
      debug:
        msg: |
          VM: {{ item.metadata.name }}
            Interfejsy (spec):
              {% for iface in item.spec.template.spec.domain.devices.interfaces | default([]) %}
              - logical_name: {{ iface.name | default('n/a') }}
                model: {{ iface.model | default('virtio') }}
                mac: {{ iface.macAddress | default('brak (MAC nie ustawiony w spec)') }}
              {% endfor %}
      loop: "{{ vm_info.resources | default([]) }}"
